#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2NjNmFiYTYwYTlhNTEwOWRkYjMwMDk1NTcxYWM3YWI5MmVmODI4YzBlNTcyMDkwNGRlNGI0MmJmNWNmZDY0OGM5MTc5MzNhMTM1YTRkNTcwY2ZjZDU5ZTAyYTJlNWI5MmM5NQ==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: https://admin:${jhipster.registry.password}@discovery.meanerror.com/eureka

zuul:
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
    connect-timeout-millis: 15000
    socket-timeout-millis: 25000
  semaphore:
    max-semaphores: 500
  routes:
    order:
      path: order/**
      serviceId: order
    
    customer:
      path: customer/**
      serviceId: custommer
      # url: order
      # strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

ribbon:
  eager-load:
    enabled: true
  eureka:
    enabled: true
  ConnectTimeout: 5000
  ReadTimeout: 120000 #2 minutes