#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2NjNmFiYTYwYTlhNTEwOWRkYjMwMDk1NTcxYWM3YWI5MmVmODI4YzBlNTcyMDkwNGRlNGI0MmJmNWNmZDY0OGM5MTc5MzNhMTM1YTRkNTcwY2ZjZDU5ZTAyYTJlNWI5MmM5NQ==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: https://admin:${jhipster.registry.password}@discovery.meanerror.com/eureka


zuul:
  routes:
    order:
      service-id: services/order/**
      path: /order/**
      url: "order"
      strip-prefix: false
    customer:
      service-id: services/customer/**
      path: /customer/**
      strip-prefix: false
      url: "customer"
    operation:
      service-id: services/operation/**
      path: /operation/**
      url: "operation"
      strip-prefix: false
    driver:
      service-id: services/driver/**
      path: /driver/**
      url: "driver"
      strip-prefix: false

