#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2NjNmFiYTYwYTlhNTEwOWRkYjMwMDk1NTcxYWM3YWI5MmVmODI4YzBlNTcyMDkwNGRlNGI0MmJmNWNmZDY0OGM5MTc5MzNhMTM1YTRkNTcwY2ZjZDU5ZTAyYTJlNWI5MmM5NQ==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: https://admin:${jhipster.registry.password}@discovery.meanerror.com/eureka


# zuul:
#   routes:
#     subway:
#       service-id: /subway/**
#       path: /subway/**
#       url: "http://localhost:7777/"
#       strip-prefix: false
#     subway1:
#       service-id: /subway1/**
#       path: /subway1/**
#       strip-prefix: false
#       url: "http://localhost:6666/"
#     subway2:
#       service-id: /subway2/**
#       path: /subway2/**
#       url: "http://localhost:5555/"
#       strip-prefix: false