#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2NjNmFiYTYwYTlhNTEwOWRkYjMwMDk1NTcxYWM3YWI5MmVmODI4YzBlNTcyMDkwNGRlNGI0MmJmNWNmZDY0OGM5MTc5MzNhMTM1YTRkNTcwY2ZjZDU5ZTAyYTJlNWI5MmM5NQ==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: https://admin:${jhipster.registry.password}@discovery.meanerror.com/eureka


zuul:
  routes:
    ordergateway:
      service-id: ordergateway
      path: /ordergateway/**
      url: /services/ordergateway/**
      strip-prefix: false

    operationgateway:
      service-id: operationgateway
      path: /operationgateway/**
      url: operationgateway
      strip-prefix: false


# zuul:
#   routes:
#     order:
#       path: /order/**
#       serviceId: order
#     customer:
#       path: /customer/**
#       serviceId: customer
#     operation:
#       path: /operation/**
#       serviceId: operation
#     driver:
#       path: /driver/**
#       serviceId: driver

    # customer:
    #   service-id: customer
    #   path: /services/customer/**
    #   url: "/services/customer/**"
    #   strip-prefix: false
    # operation:
    #   service-id: operation
    #   path: /services/operation/**
    #   url: "/services/operation/**"
    #   strip-prefix: false
    # driver:
    #   service-id: driver
    #   path: /services/driver/**
    #   url: "/services/driver/**"
    #   strip-prefix: false

