#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjljMmJkYmU0YzdlN2ExMWRlY2E4YjVmNTdlOGI2M2ZhNzBiZjY5MTk1MzI0ZDYzZTIxMTA0MzdiZTIzZWIwNzIwZGRkMDUyNzJjZjczZGFkZTRiNTE2NTAzNDhmNjYxY2U3ZQ==

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@discovery.meanerror.com/eureka/
