spring:
  application:
    name: zuul-server

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order
    customer:
      path: /customer/**
      serviceId: customer
      # url: customer
      # strip-prefix: false
