security:
    basic:
        enabled: false
    oauth2:
        client:
            accessTokenUri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/token
            userAuthorizationUri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/auth
            clientId: web_app
            clientSecret: web_app
            clientAuthenticationScheme: form
            scope: openid profile email
        resource:
            userInfoUri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/userinfo
            tokenInfoUri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/token/introspect
            preferTokenInfo: false