security:
    basic:
        enabled: false
    oauth2:
        client:
            access-token-uri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/token
            user-authorization-uri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/auth
            client-id: web_app
            client-secret: web_app
            client-authentication-scheme: form
            scope: openid profile email
        resource:
            filter-order: 3
            user-info-uri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/userinfo
            token-info-uri: https://login.meanerror.com/auth/realms/jhipster/protocol/openid-connect/token/introspect
            prefer-token-info: false
            jwt:
                key-uri: https://login.meanerror.com/auth/realms/jhipster